repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    args: [--line-length, "120"]
    language_version: python3.8

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
    exclude: ^charts/djankiserv/templates
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: debug-statements

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.0.9
  hooks:
  - id: helmlint

- repo: https://gitlab.com/retnikt/flake9
  rev: 3.8.3.post1
  hooks:
  - id: flake8
    additional_dependencies: ['toml']

- repo: https://github.com/timothycrosley/isort
  rev: 5.4.2
  hooks:
  - id: isort
